org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# [人工决策-2026-09-28 01:15:35] 私有分架构APK统一使用pubspec构建号，后续升级不受ABI偏移影响。
force-version-code-ignoring-abi=true
